syntax on
set ignorecase
set smartcase
set number
set ruler
set belloff=all
set tabstop=3

inoremap jk <ESC>
nnoremap <Enter> moO<ESC>'o
set spellfile=~/.config/vim/spell/custom.utf-8.add
" vim-plug
call plug#begin('~/vim/plugins')
Plug 'LnL7/vim-nix'
call plug#end()
