#!/bin/bash
sink=0
if [[ $@ =~ ^[+-][0-9]{,2}$ ]]; then
	actvol="$(~/.config/i3blocks/volume)"
	volume="${actvol//[!0-9]/}"
	addvol="${@//[!0-9]/}"
	[[ $@ =~ ^\+ ]] && newvol=$((volume+addvol)) && (( $newvol <= 100 )) && pactl set-sink-volume @DEFAULT_SINK@ $newvol% || newvol=$((volume-addvol)) && (( $newvol >=   0 )) && pactl set-sink-volume @DEFAULT_SINK@ $newvol%
	pkill -RTMIN+10 i3blocks
elif [[ $@ =~ ^m$ ]]; then
	pactl set-sink-mute @DEFAULT_SINK@ 1
	pkill -RTMIN+10 i3blocks
elif [[ $@ =~ ^u$ ]]; then
	pactl set-sink-mute @DEFAULT_SINK@ 0
	pkill -RTMIN+10 i3blocks
else
	echo "Wrong input format. Use \"+/-(0-99)\" for adjusting volume, \"m\" for muting and \"u\" for unmuting"
fi

