#!/bin/bash
pid="$(ps -Ao pid,user,fname,pcpu,stat,start_time,size,comm | dmenu -i -l 20 | grep -o -E '[0-9]+' | head -1)"
[ ! -z "$pid" ] && kill $pid && notify-send "process with pid <$pid> killed"
