#!/bin/bash

# Choose project name and sub-directory
projectDir="$HOME/Projekte"
projName="$(echo "" | dmenu -p 'Enter a new name: ' | tr -d '[:space:]')"
[[ "$projName" == "" ]] && exit
subDirs="$(ls -l $projectDir | awk '/^d/ {print $9}' | dmenu -p 'Select subfolder or create new one: ' | tr -d '[:space:]')"
[[ "$subDirs" == "" ]] && exit
[[ -d "$projectDir/$subDirs" ]] || mkdir "$projectDir/$subDirs"
newDir="$projectDir/$subDirs/$projName"

#nlibs="$(seq 0 9 | dmenu -p 'How many libs to add? (0 default): ')"
#[[ "$nlibs" == "" ]] && exit
template_file="$(ls $HOME/.scripts/Data/ | grep CML_ | dmenu -p 'Choose template: ')"
[[ "$template_file" == "" ]] && exit

# Create folders
mkdir $newDir
mkdir $newDir/include
mkdir $newDir/build
mkdir $newDir/build/release
mkdir $newDir/build/debug

# Fill CMakeLists.txt with stuff from template
cat $HOME/.scripts/Data/$template_file | sed s/xPROJECTNAMEx/$projName/g > "$newDir/CMakeLists.txt"
cat $HOME/.scripts/Data/dir-locals-template.txt | sed s/xPROJECTNAMEx/$projName/g | sed s/xPROJECTFOLDERx/$subDirs/g > "$newDir/.dir-locals.el"

# Generate empty files
touch $newDir/main.cpp
touch $newDir/$projName.cpp
touch $newDir/include/$projName.h

