#!/bin/bash
# description:	i3block network display
# author:	machina

output="$(nmcli connection show --active | sed -n '2p')"
name="$(echo $output | awk '{print $1}')"
interface="$(echo $output | awk '{print $4}')"
vs="\u25a0"

conn="$(nmcli networking connectivity)"


if [[ "$name" == "Ethernet" ]]; then
	[[ "$conn" == "full" ]] && printf "<span color='#E0E0E0'> " || printf "<span color='#909090'> "
	printf "[$vs$vs$vs$vs]"
elif [[ "$interface" == "wlo1" ]]; then
	[[ "$conn" == "full" ]] && printf "<span color='#E0E0E0'> " || printf "<span color='#909090'> "
	signal=$(nmcli device wifi list ifname wlo1 | grep "*")
	set -f;
	set -- $signal
	bars="${8//[_]/}"
	rep="${#bars}"
	printf "["
	if [[ $rep == "0" ]] ; then
		printf "%0.s\u25a1" $(seq 1 4)
	elif [[ $rep == "4" ]] ; then
		printf "%0.s$vs" $(seq 1 4)
	else
		printf "%0.s$vs" $(seq 1 $rep)
		printf "%0.s\u25a1" $(seq 1 $((4-rep)))
	fi
	printf "]"
else
	printf "[----]"
fi

printf "</span>\n"
