#!/bin/bash
# description:	i3block network display
# author:	machina

output="$(nmcli connection show --active | tail -1)"
name="$(echo $output | awk '{print $1}')"
interface="$(echo $output | awk '{print $4}')"
vs="\u25a0"
if [[ "$name" == "Kabelgebundene" ]]; then
	printf "[\u25a1$vs$vs\u25a1]"
elif [[ "$interface" == "wlo1" ]]; then
	signal=$(nmcli device wifi list ifname wlo1 | grep "*")
	set -f;
	set -- $signal
	bars="${8//[_]/}"
	rep="${#bars}"
	printf "["
	if [[ $rep == "0" ]] ; then
		printf "%0.s\u25a1" $(seq 1 4)
	elif [[ $rep == "4" ]] ; then
		printf "%0.s$vs" $(seq 1 4)
	else
		printf "%0.s$vs" $(seq 1 $rep)
		printf "%0.s\u25a1" $(seq 1 $((4-rep)))
	fi
	printf "]"
else
	printf "[----]"
fi

conn="$(nmcli networking connectivity)"
[[ "$conn" == "full" ]] && printf "[\u25cf]" || printf "[\u25bc]"
printf "\n"
